//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;


namespace UseCaseBasedDoku
{
    
    
    public partial class UseCaseBasedDokuLibrary : LibraryBase
    {
        
        public virtual FBMasterCopy UseCaseBasedDokuFB
        {
            get
            {
                FBMasterCopy returnValue = ((FBMasterCopy)(MasterCopies["UseCaseBasedDokuFB"]));
                return returnValue;
            }
        }
    }
    
    [OriginalTypeName("UseCaseBasedDokuFB")]
    public class UseCaseBasedDokuFB : FBMasterCopy, ITiaResource
    {
        
        public Siemens.Automation.ModularApplicationCreator.Tia.Openness.PlcDevice ParentDevice{get;set;}=null;
        
        public bool IsIncludedInTiaProject{get;set;}=true;
        
        public override string TiaProjectRootGroupName
        {
            get
            {
                return TiaDynamicProperties.ProgramBlocksRootGroupName;
            }
        }
    }
}
