//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;


namespace UseCaseBasedDoku
{
    
    
    public partial class LIBelt_V1_1_4_V17_V18_V19 : LibraryBase
    {
        
        public virtual FBMasterCopy LIBelt_Manager
        {
            get
            {
                FBMasterCopy returnValue = ((FBMasterCopy)(MasterCopies["LIBelt_Blocks.LIBelt_Manager"]));
                return returnValue;
            }
        }
    }
    
    [OriginalTypeName("LIBelt_Blocks.LIBelt_Manager")]
    public class LIBelt_Manager : FBMasterCopy, ITiaResource
    {
        
        public Siemens.Automation.ModularApplicationCreator.Tia.Openness.PlcDevice ParentDevice{get;set;}=null;
        
        public bool IsIncludedInTiaProject{get;set;}=true;
        
        public override string TiaProjectRootGroupName
        {
            get
            {
                return TiaDynamicProperties.ProgramBlocksRootGroupName;
            }
        }
    }
}
