//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;


namespace MAC_use_cases
{
    
    
    public partial class Lib_MAC_use_cases : LibraryBase
    {
        
        public virtual ProgramMasterCopy myDataType
        {
            get
            {
                ProgramMasterCopy returnValue = ((ProgramMasterCopy)(MasterCopies["myDataType"]));
                return returnValue;
            }
        }
    }
    
    [OriginalTypeName("myDataType")]
    public class myDataType : ProgramMasterCopy, ITiaResource
    {
        
        public Siemens.Automation.ModularApplicationCreator.Tia.Openness.PlcDevice ParentDevice{get;set;}=null;
        
        public bool IsIncludedInTiaProject{get;set;}=true;
        
        public override string TiaProjectRootGroupName
        {
            get
            {
                return TiaDynamicProperties.PlcDataTypesRootGroupName;
            }
        }
    }
}
