//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;


namespace MAC_use_cases
{
    
    
    public partial class Lib_MAC_use_cases : LibraryBase
    {
        
        public virtual FBLibraryType MyFunctionBlock_Typed
        {
            get
            {
                FBLibraryType returnValue = ((FBLibraryType)(Types["MyFunctionBlock_Typed"]));
                return returnValue;
            }
        }
    }
    
    [DefaultVersionGuid("37350dd3-dc9a-4954-a0dd-22084d7f0321")]
    [DefaultVersionIsIndependent(true)]
    [OriginalTypeName("MyFunctionBlock_Typed")]
    public class MyFunctionBlock_Typed : FBLibraryType, ITiaResource, ITiaProjectLibraryResource
    {
        
        public Siemens.Automation.ModularApplicationCreator.Tia.Openness.PlcDevice ParentDevice{get;set;}=null;
        
        public bool IsIncludedInTiaProject{get;set;}=true;
        
        public bool IsIncludedInProjectLibrary{get;set;}=true;
    }
}
