//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;


namespace UseCaseBasedDoku
{
    
    
    public partial class Sollas : LibraryBase
    {
        
        public virtual ProgramMasterCopy pMiddleLayer
        {
            get
            {
                ProgramMasterCopy returnValue = ((ProgramMasterCopy)(MasterCopies["pMiddleLayer"]));
                return returnValue;
            }
        }
    }
    
    [OriginalTypeName("pMiddleLayer")]
    public class pMiddleLayer : ProgramMasterCopy, ITiaResource
    {
        
        public Siemens.Automation.ModularApplicationCreator.Tia.Openness.PlcDevice ParentDevice{get;set;}=null;
        
        public bool IsIncludedInTiaProject{get;set;}=true;
        
        public override string TiaProjectRootGroupName
        {
            get
            {
                return TiaDynamicProperties.ProgramBlocksRootGroupName;
            }
        }
    }
}
