//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness.SoftwareUnit;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness.TO;
using System;


namespace MAC_use_cases
{
    
    
    public partial class Lib_MAC_use_cases : LibraryBase
    {
        
        public virtual DeviceMasterCopy S210DriveControl
        {
            get
            {
                DeviceMasterCopy returnValue = ((DeviceMasterCopy)(MasterCopies["Drives.S210DriveControl"]));
                return returnValue;
            }
        }
    }
    
    [OriginalLibraryName("Lib_MAC_use_cases")]
    [OriginalTypeName("Drives.S210DriveControl")]
    public class S210DriveControl : DeviceMasterCopy
    {
        
        public const string ORIGINAL_TYPE_NAME="Drives.S210DriveControl";
        
        public const string ORIGINAL_LIBRARY_NAME="Lib_MAC_use_cases";
        
        public override string OriginalTypeName
        {
            get
            {
                return ORIGINAL_TYPE_NAME;
            }
        }
        
        public override string OriginalLibraryName
        {
            get
            {
                return ORIGINAL_LIBRARY_NAME;
            }
        }
    }
}
