//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Siemens.Automation.ModularApplicationCreator.Tia.Helper;
using Siemens.Automation.ModularApplicationCreator.Tia.Modules;

namespace MAC_use_cases.Model
{
    /// <summary>
    /// This is generated code to extend the functionality of the EQM. Do not modify!
    /// </summary>
    public abstract partial class BaseMAC_use_casesEM : TiaEquipmentModule, ITiaAttributeUser
    {
        private void RunGeneratedTasksConstructor()
        {
        }

        private void RunGeneratedTasksInitModule()
        {
        }

        private void RunGeneratedTasksAfterEQMLoad()
        {
        }

        private void RunGeneratedBeforeDelete()
        {
        }
    }
}
