using System;
using System.Collections.Generic;
﻿using System.Collections.ObjectModel;
using System.Linq;
using Siemens.Automation.ModularApplicationCreator.Tia.Helper.Create_XML_Block.XmlBlocks.BlockFrames;
using MAC_use_cases.Model.ModuleEssentials.Example;
using MAC_use_cases.Model.UseCases;
using MAC_use_cases.Serialization;
using MAC_use_cases.ViewModel;
using Newtonsoft.Json;
using Siemens.Automation.ModularApplicationCreator.ControlModules.ModuleEssentials.Objects.Generation.Openness.XML;
using Siemens.Automation.ModularApplicationCreator.ControlModules.ModuleEssentials.Objects.Generation.Openness.XML.Parts;
using Siemens.Automation.ModularApplicationCreator.Modules;
using Siemens.Automation.ModularApplicationCreator.Serializer;
using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Helper;
using Siemens.Automation.ModularApplicationCreator.Tia.Helper.Create_XML_Block;
using Siemens.Automation.ModularApplicationCreator.Tia.Modules;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness.SoftwareUnit;
using Siemens.Automation.ModularApplicationCreator.Tia.TiaAttributeFuncs;
using Siemens.Automation.ModularApplicationCreatorBasics.Logging;
using MacPLang = Siemens.Automation.ModularApplicationCreator.Tia.Helper.Create_XML_Block.ProgrammingLanguage;
using MEPlang = Siemens.Automation.ModularApplicationCreator.ControlModules.ModuleEssentials.Objects.Generation.Openness.XML.ProgrammingLanguage;

namespace MAC_use_cases.Model
{
    /// <summary>
    ///     This is the main class in which the workflow starts. Here are all sections for creating or generating the TIA
    ///     Portal Project
    /// </summary>
    public class MAC_use_casesEM : BaseMAC_use_casesEM
    {
        /// <summary>
        /// import configuration using MAC_CLI
        /// </summary>
        /// <param name="configPath"></param>
        protected override void ApplyModuleConfiguration(string configPath)
        {
            
            base.ApplyModuleConfiguration(configPath);
            MAC_use_casesSerializer.ImportModuleFromFile(this, configPath);
        }
        /// <summary>
        ///     This attribute is the instance of the plcDevice
        /// </summary>
        private PlcDevice _plcDevice;

        private ISoftwareUnit _softwareUnit;

        // <auto-generated>
        //     This code was generated by a tool. Do not remove or modify the syntax of it.
        //     This constructor is used at first creation of this object.
        // </auto-generated>
        public MAC_use_casesEM()
        {
            // This Function can be modified to accommodate the Control Modules used in this Equipment Module
            CreateControlModules();
            // Add any code here which is needed to be used only when this object is created the first time.

            InitAfterFirstCreationOrDeserialization();

            MyTo = new TechnologyObjectClass(this);
            MyEssentialTechnologyObjectViewModel = new TechnologyObjectViewModel(new TechnologyObjectDataModel(this));
            SerializationViewModel = new SerializationViewModel(this);
        }

        // <auto-generated>
        //     This code was generated by a tool. Do not remove or modify the syntax of it.
        //     This constructor is used only for deserialization.
        // </auto-generated>
        [JsonConstructor]
        public MAC_use_casesEM(JsonConstructorMarker nullObj)
        {
            // Add any code here which is only necessary when this object is deserialized.

            InitAfterFirstCreationOrDeserialization();

            MyTo = new TechnologyObjectClass(this);
            MyEssentialTechnologyObjectViewModel = new TechnologyObjectViewModel(new TechnologyObjectDataModel(this));
            SerializationViewModel = new SerializationViewModel(this);
        }

        //-------------------------------------------
        // This ModuleStart property is generated.
        // It must be at the top of the class. It is used during module update.
        //
        // CAUTION: Do not use public instance variables as they overtake the properties in serialization.
        //-------------------------------------------
        public ModuleEdge ModuleStart
        {
            get => TopLevelEM ? new ModuleEdge() : null;
            set { }
        }

        public HardwareGenerationExcelBasedViewModel HardwareGenerationExcelBasedViewModel { get; set; } = new HardwareGenerationExcelBasedViewModel();

        [JsonIgnore]
        public SerializationViewModel SerializationViewModel { get; private set; }

        /// <summary>
        ///     This attribute is the instance of the TechnologyObjectClass
        /// </summary>
        public TechnologyObjectClass MyTo { get; set; }

        /// <summary>
        /// Gets or sets the essential data model for the technology object (Example of using Module Essentials).
        /// </summary>
        [JsonIgnore]
        public TechnologyObjectViewModel MyEssentialTechnologyObjectViewModel { get; set; }

        public bool IsGenerateHardwareChecked { get; set; } = false;

        public bool IsGenerateSafetyBlockChecked { get; set; } = false;
        /// <summary>
        ///     This attribute is the instance for the serialization
        /// </summary>
        public NonTIAProjectBased NonTiaProjectBased { get; set; } = new NonTIAProjectBased("myModel");

        /// <summary>
        ///     This attribute is the string which is used for the renaming of the FB.
        ///     This string can be changed in the View
        /// </summary>
        public string NameOfMyFb { get; set; } = "MyFunctionBlock";

        /// <summary>
        ///     This attribute is the string which is used for the renaming of the safety-FB.
        ///     This string can be changed in the View
        /// </summary>
        public string NameOfMyFailSafeFb { get; set; } = "MyFunctionBlock_FailSafe";

        /// <summary>
        ///     Controls whether additional readout from TIA Portal is required.
        ///     Set this to true when you need to read additional data after assign or update.
        /// </summary>
        public override bool IsAdditionalReadOutRequired() => false;

        [JsonIgnore]
        public ObservableCollection<string> PlcBlockNames { get; set; } = new ObservableCollection<string>();

        public override void ReadTiaPortalAfterAssignOrUpdate(TiaTemplateContext tiaTemplateContext)
        {
            base.ReadTiaPortalAfterAssignOrUpdate(tiaTemplateContext);
            GeneralSupport.ReadAdditionalInformationsFromTIAPortalProject(this, tiaTemplateContext);
        }

        [JsonIgnore]
        public string NameAndType
        {
            get => NamingConventions.CreateModuleNameAndTypeForEM("MAC_use_cases", this);
        }

        public override bool GenerateTiaPortal(TiaTemplateContext tiaTemplateContext, string generationPhaseName)
        {
            switch (generationPhaseName)
            {
                case TiaGenerationPhases.Init:
                    _plcDevice = GetPlcDevice(tiaTemplateContext);
                    break;

                    // Add equipment module specific code for each generation phase here, which is
                    // necessary before the ResourceManagement is called.
            }

            ResourceManagement.Generate(tiaTemplateContext, this, generationPhaseName);

            foreach (var module in ControlModules)
            {
                if (module is ITiaGenerateable tiaGen)
                {
                    tiaGen.GenerateTiaPortal(tiaTemplateContext, generationPhaseName);
                }
            }

            var opennessTiaPortalProject = GeneralSupport.GetOpennessProject(tiaTemplateContext.TiaProject);

            switch (generationPhaseName)
            {
                case TiaGenerationPhases.Init:

                    //if (!string.IsNullOrWhiteSpace(HardwareGenerationExcelBasedViewModel.ImportSource))
                    //{
                    //    HardwareGenerationExcelBased.CreateNewDevicesFromExcelSheet(this, opennessTiaPortalProject,
                    //        HardwareGenerationExcelBasedViewModel.ImportSource);
                    //}

                    //if (!IsGenerateHardwareChecked)
                    //{
                    //    break;
                    //}

                    //Hardware config has to be in the Init phase.Otherwise, it can't be used in the MAC.
                    var s120 = HardwareGeneration.GenerateS120(this, "S120MACTest", "S120DeviceTest",
                        "this drive is generated with MAC");

                    var s210 = HardwareGeneration.GenerateS210(this, "S210MACTest", "S210DeviceTest",
                        "this drive is generated with MAC");
                    //var subnet1 = HardwareGeneration.GetOrCreateSubnet(SubnetsManager, "PN/IE_1");

                    //HardwareGeneration.ConnectDriveToSubnet(s120, subnet1, this);
                    //HardwareGeneration.ConnectDriveToSubnet(s210, subnet1, this);

                    break;
                case TiaGenerationPhases.Build:

                    // Add equipment module specific code generation here.
                    var opennessCpu = GeneralSupport.GetOpennessDeviceItem((Siemens.Engineering.HW.Device)tiaTemplateContext.TiaDevice);
                    _softwareUnit = SoftwareUnits.GetOrCreateSoftwareUnit(_plcDevice, "MyUnit", this, "Namesapce_example");

                    // Configure a Technology Object
                    MyTo.ConfigureTO(MyTo.TechnologicalObject, this);
                    // Log messages
                    GeneralSupport.LogMessage(LogTypes.GenerationInfo, "Generate technology objects", this);
                    // Create Technology Object
                    TechnologyObjectClass.CreateTOs(_plcDevice, this);

                    IntegrateLibraries.CreateInstanceDB_via_XmlInstDB(this, ResourceManagement.MyFunctionBlock,
                        "CreatedDbFromMasterCopy_XmlInstDB", ResourceManagement.ModuleBlocksRootGroup, _plcDevice);

                    var myDataBlockGlobal =
                        GenericBlockCreation.GenerateGlobalDataBlock("MyDataBlock_Global", _plcDevice, this);

                    GenericBlockCreation.SetDefaultValue(myDataBlockGlobal.Name, "myParameterName", TIATYPE.INT, "99",
                        this);

                    GenericBlockCreation.GenerateMultiInstanceFB(_plcDevice,
                        tiaTemplateContext.TiaProject.GetEditingLanguage(), this);

                    var dbFromMasterCopy = _plcDevice.Blocks.FindBlockInPlcByName($"{nameof(ResourceManagement.MyFunctionBlock)}Db") as DataBlock
                        ?? IntegrateLibraries.CreateInstanceDataBlock(this,
                            ResourceManagement.MyFunctionBlock,
                            $"{nameof(ResourceManagement.MyFunctionBlock)}Db", ResourceManagement.ModuleBlocksRootGroup);

                    GenericBlockCreation.GenerateOB_Main(dbFromMasterCopy.Name, this,
                        tiaTemplateContext.TiaProject.GetEditingLanguage(), _plcDevice);

                    GenericBlockCreation.GenerateOBWithMultipleCalls("myOB", 10,
                        tiaTemplateContext.TiaProject.GetEditingLanguage(), _plcDevice, this);

                    GenericBlockCreation.CreateFunctionBlock($"{NameOfMyFb}_FBD", dbFromMasterCopy.Name,
                        MacPLang.FBD,
                        _plcDevice);
                    GenericBlockCreation.CreateFunctionBlock($"{NameOfMyFb}_LAD", dbFromMasterCopy.Name,
                        MacPLang.LAD,
                        _plcDevice);
                    GenericBlockCreation.CreateFunctionBlock($"{NameOfMyFb}_SCL", dbFromMasterCopy.Name,
                        MacPLang.SCL,
                        _plcDevice);

                    var dbFromFailSafeFbMasterCopy = _plcDevice.Blocks.FindBlockInPlcByName($"{nameof(ResourceManagement.MyFunctionBlock_FailSafe)}Db") as DataBlock
                        ?? IntegrateLibraries.CreateInstanceDataBlock(this,
                            ResourceManagement.MyFunctionBlock_FailSafe,
                            $"{nameof(ResourceManagement.MyFunctionBlock_FailSafe)}Db",
                            ResourceManagement.ModuleBlocksRootGroup);

                    if (IsGenerateSafetyBlockChecked)
                    {
                        GenericBlockCreation.CreateFailSafeFunctionBlock($"{NameOfMyFailSafeFb}_F_LAD",
                            dbFromFailSafeFbMasterCopy.Name,
                            MacPLang.F_LAD,
                            _plcDevice);
                    }
                    GenericBlockCreation.CreateFunctionBlockInSoftwareUnit(_softwareUnit, "MyFb_FBD",
                        MacPLang.FBD, _plcDevice);
                    GenericBlockCreation.CreateFunctionBlockInSoftwareUnit(_softwareUnit, "MyFb_LAD",
                        MacPLang.LAD, _plcDevice);
                    GenericBlockCreation.CreateFunctionBlockInSoftwareUnit(_softwareUnit, "MyFb_SCL", MacPLang.SCL, _plcDevice);

                    var dbFromTypedMasterCopy = _plcDevice.Blocks.FindBlockInPlcByName($"{nameof(ResourceManagement.MyFunctionBlock_Typed)}Db") as DataBlock
                        ?? IntegrateLibraries.CreateInstanceDataBlock(this,
                            ResourceManagement.MyFunctionBlock_Typed,
                            $"{nameof(ResourceManagement.MyFunctionBlock_Typed)}Db", ResourceManagement.ModuleBlocksRootGroup);

                    GenericBlockCreation.CreateFunctionBlock($"{nameof(ResourceManagement.MyFunctionBlock_Typed)}_FBD",
                        dbFromTypedMasterCopy.Name,
                        MacPLang.FBD,
                        _plcDevice);

                    var myTagTable = CreateVariables.CreateTagTable(_plcDevice, "myTagTable");
                    var mySoftwareUnitTagTable = CreateVariables.CreateTagTable(_softwareUnit, "mySoftwareUnitTagTable");
                    CreateVariables.CreateUserConstantInTagTable(myTagTable, "TRUE", "MY_USER_CONSTANT_1", "Bool", "My user constant comment");
                    CreateVariables.CreateTagInTagTable(myTagTable, "%I", "187", "0", "myTag_0", "Bool", "myTagComment");
                    CreateVariables.CreateTagInTagTable(mySoftwareUnitTagTable, "%I", "188", "0", "myTag_1", "Bool",
                        "myTagComment");
                    this.MyEssentialTechnologyObjectViewModel.Model.AddTechnologicalObjectParams();
                    this._plcDevice.TechnologicalObjects.GetOrCreateRootTO(MyEssentialTechnologyObjectViewModel.Model
                        .TechObjectInfo, this);

                    if (IsGenerateHardwareChecked)
                    {
                        var hmiSoftware = HardwareGeneration.GetOrCreateHMISoftware(opennessTiaPortalProject, "HMI_1");
                        IntegrateLibraries.GenerateScreenFromMastercopy(hmiSoftware,
                            ResourceManagement.Lib_MAC_use_cases.Lib_Screen_1);
                    }
                    CreateVariables.CreateUDT(
                        _plcDevice,
                        "MyUDT1",
                        "0.1",
                        new Dictionary<string, string>
                        {
                            { "TestInt",  "Int"  },
                            { "TestBool", "Bool" }
                        });

                    // Create FB with RS network in FBD
                    GenerateFbWithRSNetworkFBD("FunctionBlockRS_FBD", _plcDevice, MacPLang.FBD);

                    // Create FB with RS network in LAD (no Coil element – operand IS the output)
                    GenerateFbWithRSNetworkLAD("FunctionBlockRS_LAD", _plcDevice);

                    // Compile all types after creation
                    OpennessFuncs.CompileAllTypes(_plcDevice);

                    provider.CollectAttributes(Attributes);
                    provider.WriteValues(_plcDevice);
                    break;
            }

            return true;
        }
        
        private static SystemBlockCall CreateRSCall(XmlNetwork parent)
        {
            var rsCall = parent.AddSystemBlockCall("Rs");
            rsCall.AddCallParameter("q", "Bool", Section.Output);
            rsCall.AddCallParameter("r", "Bool", Section.Input);
            rsCall.AddCallParameter("s1", "Bool", Section.Input);
            rsCall.AddCallParameter("operand", "Bool", Section.Output);

            return rsCall;
        }

        private static SystemBlockCall CreateAssignmentCall(XmlNetwork parent)
        {
            var coil = parent.AddSystemBlockCall("Coil");
            var coilInParameter = new CustomBlockCallParameter(coil, "in", "Bool", Section.Input);
            coil.CallParameters.Add(coilInParameter);
            var coilOutParameter = new CustomBlockCallParameter(coil, "out", "Bool", Section.Output);
            coil.CallParameters.Add(coilOutParameter);
            var operandParameter = new CustomBlockCallParameter(coil, "operand", "Bool", Section.Output);
            coil.CallParameters.Add(operandParameter);
            return coil;
        }

        private static XmlNetwork CreateRSNetwork(string rInputName, string s1InputName, string outputVariableName, string rsOperandVariableName, MEPlang opnsProgrammingLanguage)
        {
            var xmlNw = new XmlNetwork(opnsProgrammingLanguage);

            var rsCall = CreateRSCall(xmlNw);

            var rInputVar = xmlNw.AddVariable(rInputName);
            xmlNw.AddConnection(rInputVar, rsCall.CallParameters.Single(x => x.Name == "r"));

            var s1InputVar = xmlNw.AddVariable(s1InputName);
            xmlNw.AddConnection(s1InputVar, rsCall.CallParameters.Single(x => x.Name == "s1"));

            var operandOutputVar = xmlNw.AddVariable(rsOperandVariableName);
            xmlNw.AddConnection(rsCall.CallParameters.Single(x => x.Name == "operand"), operandOutputVar);

            var assignmentCall = CreateAssignmentCall(xmlNw);
            xmlNw.AddConnection(rsCall.CallParameters.Single(x => x.Name.Contains("q")), assignmentCall.CallParameters.First(x => x.Name.Contains("in")));
            var assignmentOperandOutput = xmlNw.AddVariable(outputVariableName);
            xmlNw.AddConnection(assignmentCall.CallParameters.First(x => x.Name.Contains("operand")), assignmentOperandOutput);

            return xmlNw;
        }

        private static void GenerateFbWithRSNetworkFBD(string blockName, PlcDevice plcDevice, MacPLang macProgrammingLanguage)
        {
            var opnsProgrammingLanguage = (MEPlang)Enum.Parse(typeof(MEPlang), macProgrammingLanguage.ToString());

            var block = new XmlFB(blockName);
            block.BlockAttributes.ProgrammingLanguage = macProgrammingLanguage;

            // Inputs: R and S1 for the first RS, R2 for the second RS
            block.Interface[InterfaceSections.Input].Add(new InterfaceParameter("InputBool_R", "Bool"));
            block.Interface[InterfaceSections.Input].Add(new InterfaceParameter("InputBool_S1", "Bool"));
            block.Interface[InterfaceSections.Input].Add(new InterfaceParameter("InputBool_R2", "Bool"));

            var staticItf = block.Interface[InterfaceSections.Static];
            staticItf.Add(new InterfaceParameter("RSOperand", "Bool"));
            staticItf.Add(new InterfaceParameter("OutputBool", "Bool"));
            staticItf.Add(new InterfaceParameter("RSOperand2", "Bool"));
            staticItf.Add(new InterfaceParameter("OutputBool2", "Bool"));

            // Network 1: first RS flip-flop
            var rsNetwork1 = CreateRSNetwork("#InputBool_R", "#InputBool_S1", "#OutputBool", "#RSOperand", opnsProgrammingLanguage);
            block.Networks.Add(rsNetwork1.GenerateFixNetwork());

            // Network 2: second RS flip-flop – S1 is driven by #OutputBool written in Network 1
            var rsNetwork2 = CreateRSNetwork("#InputBool_R2", "#OutputBool", "#OutputBool2", "#RSOperand2", opnsProgrammingLanguage);
            block.Networks.Add(rsNetwork2.GenerateFixNetwork());

            block.GenerateXmlBlock(plcDevice);
        }

        /// <summary>
        /// Generates an FB with two RS networks in LAD language.
        /// In LAD the Q output of RS is left unconnected (null) and the operand pin
        /// carries the bit-memory result – no separate Coil element is used.
        /// </summary>
        private static void GenerateFbWithRSNetworkLAD(string blockName, PlcDevice plcDevice)
        {
            var block = new XmlFB(blockName);
            block.BlockAttributes.ProgrammingLanguage = MacPLang.LAD;

            block.Interface[InterfaceSections.Input].Add(new InterfaceParameter("InputBool_R", "Bool"));
            block.Interface[InterfaceSections.Input].Add(new InterfaceParameter("InputBool_S1", "Bool"));
            block.Interface[InterfaceSections.Input].Add(new InterfaceParameter("InputBool_R2", "Bool"));

            var staticItf = block.Interface[InterfaceSections.Static];
            staticItf.Add(new InterfaceParameter("RSOperand", "Bool"));
            staticItf.Add(new InterfaceParameter("RSOperand2", "Bool"));

            // Network 1: RS flip-flop in LAD
            var rsNetwork1 = CreateRSNetworkLAD("#InputBool_R", "#InputBool_S1", "#RSOperand");
            block.Networks.Add(rsNetwork1.GenerateFixNetwork());

            // Network 2: RS flip-flop in LAD – S1 driven by the operand written in Network 1
            var rsNetwork2 = CreateRSNetworkLAD("#InputBool_R2", "#RSOperand", "#RSOperand2");
            block.Networks.Add(rsNetwork2.GenerateFixNetwork());

            block.GenerateXmlBlock(plcDevice);
        }

        /// <summary>
        /// Creates a single RS network intended for use inside a LAD-language FB.
        /// <para>
        /// Note: <see cref="XmlNetwork"/> must be constructed with <see cref="MEPlang.FBD"/> even for
        /// LAD blocks. LAD and FBD share the same underlying graph XML schema in TIA Portal's
        /// Openness import format. Passing <see cref="MEPlang.LAD"/> to <see cref="XmlNetwork"/>
        /// produces XML that TIA Portal rejects with a <see cref="System.Xml.XmlException"/> at
        /// import time. The block-level <c>ProgrammingLanguage</c> attribute set in
        /// <see cref="GenerateFbWithRSNetworkLAD"/> is what causes TIA Portal to display the block
        /// in LAD view.
        /// </para>

        /// </summary>
        private static XmlNetwork CreateRSNetworkLAD(string rInputName, string s1InputName, string rsOperandVariableName)
        {
            // XmlNetwork must use FBD here: LAD and FBD share the same underlying graph XML in
            // TIA Portal. XmlNetwork(MEPlang.LAD) generates a schema TIA Portal rejects on import.
            var xmlNw = new XmlNetwork(MEPlang.FBD);

            var rsCall = CreateRSCall(xmlNw);

            var rInputVar = xmlNw.AddVariable(rInputName);
            xmlNw.AddConnection(rInputVar, rsCall.CallParameters.Single(x => x.Name == "r"));

            var s1InputVar = xmlNw.AddVariable(s1InputName);
            xmlNw.AddConnection(s1InputVar, rsCall.CallParameters.Single(x => x.Name == "s1"));

            var operandOutputVar = xmlNw.AddVariable(rsOperandVariableName);
            xmlNw.AddConnection(rsCall.CallParameters.Single(x => x.Name == "operand"), operandOutputVar);

            // Q output left unconnected – required for RS in LAD (no downstream Coil element)
            xmlNw.AddConnection(rsCall.CallParameters.Single(x => x.Name == "q"), null);

            return xmlNw;
        }
    }
}
