// <auto-generated>
// This file is a placeholder for the UDT wrapper that would be
// generated from a TIA Portal library. It allows the C# project
// to reference the UDT before it has been formally created in the library.
// </auto-generated>

using Siemens.Automation.ModularApplicationCreator.Tia;
using Siemens.Automation.ModularApplicationCreator.Tia.Openness;

namespace MAC_use_cases.TiaImports.GeneratedClasses.RTU
{
    // Note: The actual UDT in TIA Portal should contain the following members
    // based on the SDS for EM-500:
    //
    // DirtyFilter_DI: Bool (Input)

    public partial class Lib_MAC_use_cases
    {
        public virtual ProgramMasterCopy UDT_EM500_Interface
        {
            get
            {
                return ((ProgramMasterCopy)(MasterCopies["UDT_EM500_Interface"]));
            }
        }
    }

    [OriginalTypeName("UDT_EM500_Interface")]
    public class UDT_EM500_Interface : ProgramMasterCopy, ITiaResource
    {
        public PlcDevice ParentDevice { get; set; } = null;
        public bool IsIncludedInTiaProject { get; set; } = true;

        public override string TiaProjectRootGroupName
        {
            get
            {
                return TiaDynamicProperties.PlcDataTypesRootGroupName;
            }
        }
    }
}
